all:
	g++ delaunayimagewriter.cpp vertex.cpp edge.cpp triangle.cpp -o delaunay_imagemaker -std=c++11
	g++ delaunayapp.cpp vertex.cpp edge.cpp triangle.cpp -o delaunay_app -std=c++11
imagemaker:
	g++ delaunayimagewriter.cpp vertex.cpp edge.cpp triangle.cpp -o delaunay_imagemaker -std=c++11
appwindow:
	g++ delaunayapp.cpp vertex.cpp edge.cpp triangle.cpp -o delaunay_app -std=c++11